# Generated by cpp11: do not edit by hand

cpp11_ComputeFoldChange <- function(matrix, features, labels, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads) {
  .Call(`_fastde_cpp11_ComputeFoldChange`, matrix, features, labels, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads)
}

cpp11_ComputeFoldChangeSparse <- function(x, i, p, features, rows, cols, labels, features_as_rows, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads) {
  .Call(`_fastde_cpp11_ComputeFoldChangeSparse`, x, i, p, features, rows, cols, labels, features_as_rows, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads)
}

cpp11_ComputeFoldChangeSparse64 <- function(x, i, p, features, rows, cols, labels, features_as_rows, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads) {
  .Call(`_fastde_cpp11_ComputeFoldChangeSparse64`, x, i, p, features, rows, cols, labels, features_as_rows, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads)
}

cpp11_FilterFoldChange <- function(fc, pct1, pct2, init_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, not_count, threads) {
  .Call(`_fastde_cpp11_FilterFoldChange`, fc, pct1, pct2, init_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, not_count, threads)
}

cpp11_FilterFoldChangeMat <- function(fc, pct1, pct2, init_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, not_count, threads) {
  .Call(`_fastde_cpp11_FilterFoldChangeMat`, fc, pct1, pct2, init_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, not_count, threads)
}

cpp11_sp_transpose <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp_transpose`, x, i, p, nrow, ncol, threads)
}

cpp11_sp64_transpose <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp64_transpose`, x, i, p, nrow, ncol, threads)
}

cpp11_sp_to_dense <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp_to_dense`, x, i, p, nrow, ncol, threads)
}

cpp11_sp64_to_dense <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp64_to_dense`, x, i, p, nrow, ncol, threads)
}

cpp11_sp_to_dense_transposed <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp_to_dense_transposed`, x, i, p, nrow, ncol, threads)
}

cpp11_sp64_to_dense_transposed <- function(x, i, p, nrow, ncol, threads) {
  .Call(`_fastde_cpp11_sp64_to_dense_transposed`, x, i, p, nrow, ncol, threads)
}

cpp11_sp_rbind <- function(xvecs, ivecs, pvecs, nrows, ncols, threads) {
  .Call(`_fastde_cpp11_sp_rbind`, xvecs, ivecs, pvecs, nrows, ncols, threads)
}

cpp11_sp64_rbind <- function(xvecs, ivecs, pvecs, nrows, ncols, threads) {
  .Call(`_fastde_cpp11_sp64_rbind`, xvecs, ivecs, pvecs, nrows, ncols, threads)
}

cpp11_sp_cbind <- function(xvecs, ivecs, pvecs, nrows, ncols, threads) {
  .Call(`_fastde_cpp11_sp_cbind`, xvecs, ivecs, pvecs, nrows, ncols, threads)
}

cpp11_sp64_cbind <- function(xvecs, ivecs, pvecs, nrows, ncols, threads) {
  .Call(`_fastde_cpp11_sp64_cbind`, xvecs, ivecs, pvecs, nrows, ncols, threads)
}

cpp11_sp_colSums <- function(x, p, threads) {
  .Call(`_fastde_cpp11_sp_colSums`, x, p, threads)
}

cpp11_sp64_colSums <- function(x, p, threads) {
  .Call(`_fastde_cpp11_sp64_colSums`, x, p, threads)
}

cpp11_sp_rowSums <- function(x, i, nrows, threads) {
  .Call(`_fastde_cpp11_sp_rowSums`, x, i, nrows, threads)
}

cpp11_dense_ttest <- function(input, features, labels, alternative, var_equal, as_dataframe, threads) {
  .Call(`_fastde_cpp11_dense_ttest`, input, features, labels, alternative, var_equal, as_dataframe, threads)
}

cpp11_sparse_ttest <- function(x, i, p, features, rows, cols, labels, features_as_rows, alternative, var_equal, as_dataframe, threads) {
  .Call(`_fastde_cpp11_sparse_ttest`, x, i, p, features, rows, cols, labels, features_as_rows, alternative, var_equal, as_dataframe, threads)
}

cpp11_sparse64_ttest <- function(x, i, p, features, rows, cols, labels, features_as_rows, alternative, var_equal, as_dataframe, threads) {
  .Call(`_fastde_cpp11_sparse64_ttest`, x, i, p, features, rows, cols, labels, features_as_rows, alternative, var_equal, as_dataframe, threads)
}

cpp11_dense_wmw <- function(input, features, labels, rtype, continuity_correction, as_dataframe, threads) {
  .Call(`_fastde_cpp11_dense_wmw`, input, features, labels, rtype, continuity_correction, as_dataframe, threads)
}

cpp11_sparse_wmw <- function(x, i, p, features, rows, cols, labels, features_as_rows, rtype, continuity_correction, as_dataframe, threads) {
  .Call(`_fastde_cpp11_sparse_wmw`, x, i, p, features, rows, cols, labels, features_as_rows, rtype, continuity_correction, as_dataframe, threads)
}

cpp11_sparse64_wmw <- function(x, i, p, features, rows, cols, labels, features_as_rows, rtype, continuity_correction, as_dataframe, threads) {
  .Call(`_fastde_cpp11_sparse64_wmw`, x, i, p, features, rows, cols, labels, features_as_rows, rtype, continuity_correction, as_dataframe, threads)
}
