# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FoldChangeBatch <- function(matrix, labels, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads) {
    .Call(`_bigde_FoldChangeBatch`, matrix, labels, calc_percents, fc_name, use_expm1, min_threshold, use_log, log_base, use_pseudocount, as_dataframe, threads)
}

wmwfast <- function(matrix, labels, rtype, continuity_correction, as_dataframe, threads) {
    .Call(`_bigde_wmwfast`, matrix, labels, rtype, continuity_correction, as_dataframe, threads)
}

